### ISSUE TITLE
支持pro版本和v9api吗

### ISSUE THREAD

**Issue by JackuXL** [pboymt/autojs-dev#20]

**Comment by pboymt** [comment]
Pro支持，v9没有，最近用不上了所以没有更新

**Comment by JackuXL** [comment]
ok谢谢

**Comment by pboymt** [comment]
我记得好像可以直接用v9提供的types吧，好像提供了。

**Comment by pboymt** [comment]
https://www.npmjs.com/package/@autojs/types-pro8

https://www.npmjs.com/package/@autojs/types-pro9

autojs-dev的工具链应该是识别这两个库的。
