### ISSUE TITLE
如何来调用autojs内置函数

### ISSUE THREAD

**Issue by yjjdick** [pboymt/autojs-dev#22]
我调用toast build编译说找不到toast

**Comment by pboymt** [comment]
版本号？如果不是beta版本，请自行安装`@autojs/types-pro8`或者`@autojs/types-pro9`，或者直接使用beta版本。

```bash
npm i -D @autojs/types-pro8
# 或
npm i -D @autojs/types-pro8
# 或
npm i -g autojs-dev@beta
```

**Comment by yjjdick** [comment]
> 版本号？如果不是beta版本，请自行安装`@autojs/types-pro8`或者`@autojs/types-pro9`，或者直接使用beta版本。
> 
> ```shell
> npm i -D @autojs/types-pro8
> # 或
> npm i -D @autojs/types-pro8
> # 或
> npm i -g autojs-dev@beta
> ```

谢谢你的回答，我用的是autox.js，因为autox是基于auto.js的，auto.js只支持ES5，我想用Npm来管理包和使用ES6,7的语法，但是这个好像和autox.js没有什么关系，因为我还没有关联到autox.js的编译器中，我想用您的工程来跑下最简单的toast，所以我需要再安装一下npm i -D @autojs/types-pro8是吗

**Comment by yjjdick** [comment]
> 版本号？如果不是beta版本，请自行安装`@autojs/types-pro8`或者`@autojs/types-pro9`，或者直接使用beta版本。
> 
> ```shell
> npm i -D @autojs/types-pro8
> # 或
> npm i -D @autojs/types-pro8
> # 或
> npm i -g autojs-dev@beta
> ```

我好像解决了，你现在是只支持pro版本吗，希望以后可以支持auto.js版本，那本框架不维护了，pro他们收费了好像自己就支持typescript，你这个框架做的很好，感谢
