### ISSUE TITLE
build 初始工程就报错了

### ISSUE THREAD

**Issue by Coande** [pboymt/autojs-dev#5]
报错如下：
> WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

**Comment by pboymt** [comment]
这个大概率是webpack的版本问题了，我抽空看看怎么解决。也有可能是不小心调用了全局webpack

**Comment by Coande** [comment]
排除调用了全局 webpack 的可能，没有全局安装的 webpack

**Comment by SalterYu** [comment]
一样的问题

**Comment by zhangzw218** [comment]
> 这个大概率是webpack的版本问题了，我抽空看看怎么解决.也有可能是不小心调用了全局webpack
遇到了同样的问题

**Comment by hanayashiki** [comment]
webpack 到底该第几个版本？^4.30 还是太高吧？
