### ISSUE TITLE
declare module 'global' 无法正常被解析

### ISSUE THREAD

**Issue by flyguolai** [pboymt/autojs-dev#7]
autojs.d.ts文件中declare module 'global' 无法正常被ts文件解析，而js文件可以正常解析并使用该声明文件。。

默认create的是ts文件，引用了autojs.d.ts，发现无法正常引用以及build

最后手动改用的 auto.d.ts文件，引用正常并且build也通过

**Comment by pboymt** [comment]
主要是因为TypeScript经历版本改动导致有一个用不了了，3.0的时候两个都能用

**Comment by flyguolai** [comment]
我丢几个pr上来你看看咋样
